### ISSUE TITLE
[Document] KCL doc Spec

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kclvm-go#156]
## Doc Representation And Generation Spec

1. This is the **specification of the document format of KCL package** and restricts **the best practice of KCL package and schema design**. It requires the package owners and the schema developers to provide key information to their users: package introduction, schema description and examples, etc.
2. This defines the way `kpm` and `doc` tools read and parse the KCL packages and generate documentation.

A typical KCL package has the following directory structure:

```
packageRoot
├── subPackage
│   ├── fileA.k
│   └── ...
├── fileB.k
├── ...
├── kcl.mod
└── README.md
```
### package doc spec

Define the package's meta information in the kcl.mod file: name, version, short description, dependencies, etc. :

```
[package]
name = "hello_world" # the name of the package
version = "0.1.0"    # the current version, obeying semver
edition = "0.5.0"    # the KCL compiler version
description = "A KCL hello world project" # the brief description of the package
```

Define detailed description of the package in the README.md file, which can include richer media such as badges and images.

### docstring spec
```
"""
model_description: 不包含三引号的字符串，可使用 markdown

Attributes
---------
<attribute_name>: <attribute_description>

Examples
--------
A brief description of the example code
```
<code_example>
```

See Also
--------
<http_link>
<sample_directory_path>
"""
```

### example spec

In addition to schema docstring, the example usages can be defined in the `examples(_name).k` file in the same directory as the schema file.

```
import a.b.c

"""
A description of the example: when to use it, what it solves
"""
example_<schema_name>_XXX = c.<schema_name>{
    # ...
}
```

### output spec

From KCL schema source code, extract and generate readable documents in various formats, mainly including Markdown and Html. Take Markdown as an example:

```
package.md
├── Schemas
│   ├── SchemaA.md
│   └── SchemaB.md
├── Rules
│   ├── RuleC.md
│   └── RuleD.md
└── Protocols
    ├── ProtocolE.md
    └── ProtocolF.md
```

#### the generated package document

The package document is the home page of the package, which contains three chapters: README, Documentation and Source Files.
- The README section comes from readme.md in the package root
- Documentation section:
  - Overview package description in the package doc spec
  - Index serves as the package index page, pointing to subpackages and schema/rules/protocol
- Source Files section
- Indicates the source code of the current package

```
## README

Rendered as the homepage of the package.

## Documentation

### Overview

A brief overview of the package

### Index

Indexes to all the schemas/protocols/rules in this package

## Source Files

- [package](source file link to the package)
```

#### the generated schema document

```
## Documentation

### Overview

A description of the schema

### Parent Schema(optional) 

[parent_schema_name](link to the parent schema doc)

### Parameters(optional) 

**`parameter_name`** type

## Attributes

**`attr_name`** *deprecated* *required* *readonly*
`basic_type` or [schema_type](link to schema type)
A description of the attribute
Default: `value` or ```multiple lines value```

## Examples

**`example_name`**
A brief description of the example code

\`\`\`
<code_example>
\`\`\`

## Source Files

- [schema definition](source file link to schema)
- [schema examples](source file to schema examples)
```

**Comment by Peefy** [comment]
Does this document need to be updated to the KCL website? cc @amyXia1994
