### ISSUE TITLE
[Enhancement] doc tool generate provides `referenced by` information on schema

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kclvm-go#165]
## Enhancement

That will be helpful to navigate from schema and its usages to get an overview of a schema

**Comment by shruti2522** [comment]
Hey @Peefy, I noticed there's a `Ref` field already specified within `KclOpenAPIType`. Are we considering using it for displaying the `referenced by` information on the schema?

**Comment by Peefy** [comment]
I am not sure that the filed has been used. The basic and related issue is https://github.com/kcl-lang/kcl/issues/1215 You can give a try. Thank you @shruti2522 ❤
