### ISSUE TITLE
[Enhancement] Add AllOf validations for KCL jsonschema generations

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kclvm-go#212]
## Before

+ kcl-go/pkg/tools/gen/types.go

```go
type validation struct {
	Name             string
	Minimum          *float64
	ExclusiveMinimum bool
	Maximum          *float64
	ExclusiveMaximum bool
	MinLength        *int
	MaxLength        *int
	Regex            *regexp.Regexp
	MultiplyOf       *int
	Unique           bool
}
```

+ After

```go
type validation struct {
	Name             string
	Minimum          *float64
	ExclusiveMinimum bool
	Maximum          *float64
	ExclusiveMaximum bool
	MinLength        *int
	MaxLength        *int
	Regex            *regexp.Regexp
	MultiplyOf       *int
	Unique           bool
        AllOf   []*validation
}
```

**Comment by jakezhu9** [comment]
For allOf keyword, a basic use case coule be:
```
{
  "allOf": [
    { "type": "string" },
    { "minLength": 2 }
  ]
}
```
In this case, the desgin to add AllOf validations is great. However, things get complicated if it is:
```
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "name": { "type": "string" }
      }
    },
    {
      "type": "object",
      "properties": {
        "address": { "type": "string" }
      }
    }
  ]
}
```
In this case, just adding some validation rules doesn't seem to be enough. Even worse, in some real-world situations, allOf is used with other conditional keywords (not, if, then...) For example in github workflow schema:
```
 "allOf": [
    {
        "if": {
            "properties": {
                "type": {
                    "const": "boolean"
                }
            },
            "required": [
                "type"
            ]
        },
        "then": {
            "properties": {
                "default": {
                    "type": "boolean"
                }
            }
        },
        "else": {
            "properties": {
                "default": {
                    "type": "string"
                }
            }
        }
    }
    ...
```
I'm not quite sure if it can all be perfectly converted to KCL. And more design and transformation rules is needed. I'm currently working on improving the import tool (#200) and have made some progress. Maybe later we can have further communication on how to make it better :)

**Comment by Peefy** [comment]
Great job 👍 For complex validation combinations, my current idea is to aim to connect 5 typical use cases, such as the GitHub workflow JSON schema. For specific implementation, we can first represent the input and output of some typical cases. 

Of course, for some corner cases, there may indeed be conversion difficulties that need to be viewed separately.

Here's some references

+ CUE extract test data: https://github.com/cue-lang/cue/tree/master/encoding/jsonschema/testdata

**Comment by shikharish** [comment]
@Peefy Hello, I would like to work on this issue. I am new to the project so can you please give me an overview of the issue.

**Comment by EraKin575** [comment]
If this issue is still relevant, I would like to work on it!
