### ISSUE TITLE
program CI needs a coverage check to guarantee quality

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kclvm-go#22]
## Enhancement

program CI needs a coverage check to guarantee pass quality, for example, modified code should have a >95 coverage

**Comment by jakezhu9** [comment]
We now have Coveralls to analyse code coverage and share reports for each pull request. (for example https://github.com/kcl-lang/kcl-go/pull/126#issuecomment-1660248407). I think our focus should be on enhancing our test coverage.

**Comment by amyXia1994** [comment]
@jakezhu9 good job! 👍
