### ISSUE TITLE
error get depends

### ISSUE THREAD

**Issue by reckless-huang** [kcl-lang/kclvm-go#253]
<img width="1306" alt="image" src="https://github.com/kcl-lang/kcl-go/assets/53162954/7378eedd-5142-4bf0-823c-e5fbbefac7c5">

**Comment by reckless-huang** [comment]
https://kcl-lang.io/zh-CN/blog/2023-new-version-feature-interpretation-kclvm-go-feature-overview/    needupdate

**Comment by Peefy** [comment]
Hi @reckless-huang 

The kcl-go repository has been migrated. 
+ Before v0.4.4, you can run `go get kusionstack.io/kclvm-go@0.4.4`
+ After v0.4.4, you can run `go get kcl-lang.io/kcl-go@main`
