### ISSUE TITLE
Inconsistent native and service KCL api `ParseFile` behaviour

### ISSUE THREAD

**Issue by bozaro** [kcl-lang/kclvm-go#260]
## Bug Report

Native KCL api `ParseFile` method returns rust panicked error.

### 1. Minimal reproduce step (Required)

Test for reproduce: https://github.com/bozaro/kcl-parse-file-issue/blob/master/kcl_parse_file_issue_test.go

1. Clone repository:
```
git clone https://github.com/bozaro/kcl-parse-file-issue.git .
```
2. Run test:
```
go test -v .
```

### 2. What did you expect to see? (Required)
I expect to see same result for native and service tests.

### 3. What did you see instead (Required)
Native client returns rust panicked error with kcl parse non-empty errors case:
```
=== RUN   Test
=== RUN   Test/pygrpc
=== RUN   Test/pygrpc/simple
=== RUN   Test/pygrpc/pkgpath_not_found
=== RUN   Test/native
=== RUN   Test/native/simple
=== RUN   Test/native/pkgpath_not_found
thread '<unnamed>' panicked at api/src/service/capi.rs:154:5:
called `Result::unwrap()` on an `Err` value: NulError(7238, [10, 139, 55,..., 111, 39, 18, 0])
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    kcl_parse_file_issue_test.go:64: 
        	Error Trace:	/home/bozaro/xxx/xxa/kcl_parse_file_issue_test.go:64
        	Error:      	ParseFile returns error: %s
        	Test:       	Test/native/pkgpath_not_found
        	Messages:   	called `Result::unwrap()` on an `Err` value: NulError(7238, [10, 139, 55, 123, 34, 102, 105, 108, 10
--- FAIL: Test (0.01s)
    --- PASS: Test/pygrpc (0.00s)
        --- PASS: Test/pygrpc/simple (0.00s)
        --- PASS: Test/pygrpc/pkgpath_not_found (0.00s)
    --- FAIL: Test/native (0.00s)
        --- PASS: Test/native/simple (0.00s)
        --- FAIL: Test/native/pkgpath_not_found (0.00s)
FAIL
FAIL	github.com/bozaro/kcl-parse-file-issue	0.014s
FAIL
```

### 4. What is your KCL components version? (Required)
```
kcl-lang.io/kcl-go v0.8.1
```

**Comment by Peefy** [comment]
Thank you for your feedback. I will investigate and fix it.

**Comment by Peefy** [comment]
Fixed in https://github.com/kcl-lang/kcl/pull/1145. After my investigation, I found that it was due to the C API call using protobuf as a protocol conversion and encountering an unexpected 0 byte.
