### ISSUE TITLE
[Enhancement] kcl import muti yaml resource

### ISSUE THREAD

**Issue by reckless-huang** [kcl-lang/kclvm-go#266]
There are three resources written in one YAML file deployment + service + pvc split with '---'
````
deployment
___
service
___
pvc 
````
then kcl import -f  xxx 
only convert the  deployment ， not all

**Comment by Peefy** [comment]
Thank you for the feedback. This is a pending issue, PRs welcome. ❤️

**Comment by Peefy** [comment]
The code is here: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_yaml.go

**Comment by reckless-huang** [comment]
> The code is here: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_yaml.go

I’ll give it a try.
